//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstVillain.Entities
{
    
    
    public class JStageItemEffectData
    {
        
        public int Id;
        
        public string ItemType;
        
        public string EffectType;
        
        public int Value;
    }
}
